variables:
  # Docker Registry Configuration
  DOCKER_REG: gitlab.mynode.space:1443
  CONTAINER_IMAGE: ${DOCKER_REG}/browsergame/bg-backend/api
  CONTAINER_IMAGE_BACKEND: ${DOCKER_REG}/browsergame/bg-backend/api

  # Database Configuration
  POSTGRES_DB: cicd_db
  POSTGRES_USER: random_user
  POSTGRES_PASSWORD: super_secure_password

  # .NET Configuration
  #DOTNET_CLI_HOME: "/tmp/DOTNET_CLI_HOME"
  #NUGET_PACKAGES: ".nuget/packages"
