include:
  - local: ".gitlab/ci/variables.gitlab-ci.yml"
  - local: ".gitlab/ci/migrations.gitlab-ci.yml"
  - local: ".gitlab/ci/test.gitlab-ci.yml"

stages:
  - "build"
  - "test"
  - "package"

# Build stage
build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - dotnet restore
    - dotnet build
  artifacts:
    paths:
      - src/BG.API/bin/
  cache:
    key: ${CI_COMMIT_REF_SLUG}-nuget
    paths:
      - .nuget/packages

# Test stages
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  needs:
    - build
  script:
    - dotnet restore
    - dotnet test --filter "Category!=Integration" --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "junit;LogFilePath=./TestResults/results.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    reports:
      #coverage_report:
      #  coverage_format: cobertura
      #  path: "**/coverage.cobertura.xml"
      junit: "**/TestResults/results.xml"
    when: always

# Package stage
package:
  stage: package
  image: gcr.io/kaniko-project/executor:debug
  needs:
    - unit-test
    - integration-test
  script:
    - /kaniko/executor
      --context .
      --dockerfile deploy/docker/backend.Dockerfile
      --destination $CONTAINER_IMAGE:$CI_COMMIT_SHA
      --destination $CONTAINER_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"

# Pipeline triggers
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
