
stages:
  - build
  - docker
  - deploy
  - stop_deploy






# BUILD  ############################################################################
# cache nuget template
.cache_nuget: &cache_nuget
  # https://gitlab.com/gitlab-org/gitlab-ci-yml/issues/12
  variables:
    NUGET_PACKAGES: "${CI_PROJECT_DIR}/.nugetcache"

  cache: # https://docs.gitlab.com/ce/ci/yaml/README.html#cache
    paths:
#      - .local/share/NuGet/Cache
#      - .nuget/packages
      - .nugetcache
    key: "nuget"

job_build_dotnet_bin_linux:
  stage: build
  image: microsoft/dotnet:latest
  <<: *cache_nuget

  script: 
    - cd Backend/
    - dotnet restore
    - dotnet publish
        ApiServer/ApiServer.csproj
        --self-contained
        -c Release
        --framework netcoreapp2.0
        -r ubuntu.16.10-x64

  artifacts:
    expire_in: 60 minutes
    paths:
      - Backend/ApiServer/bin/Release/*


## scripts for type/javascript
job_build_vue:
  stage: build
  image: node:7
  # require runner with npm tag - nothing special only for caching
  tags:
    - npm

  before_script:
    - cd Frontend/
    - npm install

  script:
    - npm run build

  # cache node_modules for faster build times
  cache:
    paths:
      - Frontend/node_modules/
    key: "npm-vue"

  artifacts:
      expire_in: 15 minutes
      paths:
        - Frontend/*.html
        - Frontend/dist/*
        - Frontend/images/*


## create postman docs
# https://stackoverflow.com/questions/29238120/creating-html-doc-from-postman-collection
job_build_postman_docs:
  stage: build
  image: 
    name: hughmp/postmanerator:latest
    # ATTENTION: this container hash no shell as entrypoint -> set it ( https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image )
    entrypoint: [""]

  allow_failure: true

  # need to use correct container typ for: https://github.com/postmanlabs/postman-collection-transformer
  before_script:
    - apk add --update nodejs nodejs-npm
    - npm install -g postman-collection-transformer
  
  script:
    - node /usr/bin/transform-collection.js --help
    - node /usr/bin/transform-collection.js convert --help
    - node /usr/bin/transform-collection.js convert -i="./docs/RestAPI/BrowsergameAPI.postman_collection.json" -j="2.1.0" -o="./docs/RestAPI/BrowsergameAPI.V1.postman_collection.json" -p="1.0.0" -P -w
    - find . -name "*.json"
    - postmanerator -output=./doc.html -collection=./docs/RestAPI/BrowsergameAPI.postman_collection.json -environment=./docs/RestAPI/BrowsergameAPI.postman_environment.json

  artifacts:
      expire_in: 45 minutes
      paths:
        - ./*.html








# DOCKER  ############################################################################
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-the-gitlab-container-registry
job_docker_create:
  stage: docker
  image: docker:stable
  
#  dependencies:
#    - job_package_ubuntu
  dependencies:
    - job_build_dotnet_bin_linux
    - job_build_vue

  # require runner with dind tag
  tags:
    - dind
  services:
    # - docker:dind
    # https://github.com/LordGaav/dind-options
    - lordgaav/dind-options:latest


  variables:
    # gitlab.mynode.space:1443/browsergame/browsergame:tag
    CONTAINER_IMAGE: 10.0.0.130:1443/browsergame/browsergame:$CI_COMMIT_REF_SLUG
    
    # When using dind service we need to instruct docker, to talk with the
    # daemon started inside of the service. The daemon is available with
    # a network connection instead of the default /var/run/docker.sock socket.
    #
    # The 'docker' hostname is the alias of the service container as described at
    # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
    #
    # Note that if you're using Kubernetes executor, the variable should be set to
    # tcp://localhost:2375 because of how Kubernetes executor connects services
    # to the job container
    #DOCKER_HOST: tcp://docker:2375/
    DOCKER_HOST: "tcp://lordgaav__dind-options:2375"

    # When using dind, it's wise to use the overlayfs driver for
    # improved performance.
    DOCKER_DRIVER: overlay2

    # https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry
    DOCKER_OPTS: "--insecure-registry=10.0.0.130:1443"
  
  before_script:
    # login to registy
    # - docker info
    - docker login -u "$DOCKER_REG_USER" -p "$DOCKER_REG_PASSWORD" $CONTAINER_IMAGE

  script:
    - docker pull $CONTAINER_IMAGE || true
    
    #-------------------------------------------------------------------------------
    # copy artifact to docker build dir
    - mkdir -p ./Docker
    - mv -v Backend/ApiServer/bin/Release/netcoreapp2.0/ubuntu.16.10-x64/publish/* ./Docker/

    # vue stuff
    - mkdir -p ./Docker/wwwroot/dist
    - mkdir -p ./Docker/wwwroot/images
    - cp -Rv Frontend/*.html ./Docker/wwwroot
    - cp -Rv Frontend/dist/*.js ./Docker/wwwroot/dist/
    - cp -Rv Frontend/images/* ./Docker/wwwroot/images/
    #-------------------------------------------------------------------------------
    - ls -ahl && ls -ahl ./Docker/
    # build container
    - docker build -t $CONTAINER_IMAGE ./Docker/
    - docker push $CONTAINER_IMAGE







# DEPLOY  ############################################################################
# idea: https://stackoverflow.com/questions/44545635/how-to-auto-deploy-docker-image-on-own-server-with-gitlab
# image: https://hub.docker.com/r/kroniak/ssh-client/
job_deploy_staging:
  stage: deploy
  image: kroniak/ssh-client

  allow_failure: true

  dependencies:
    - job_docker_create

  variables:
  #  GIT_STRATEGY: none # we need git for docker-compose

    CONTAINER_IMAGE: 10.0.0.130:1443/browsergame/browsergame:$CI_COMMIT_REF_SLUG
    DOCKER_CONTAINER_NAME: browsergame_$CI_COMMIT_REF_SLUG
    VHOST: $CI_COMMIT_REF_SLUG.gamez.mynode.space

  environment:
    name: staging/$CI_COMMIT_REF_SLUG
    url: http://$CI_COMMIT_REF_SLUG.gamez.mynode.space
    on_stop: job_stop_deploy_staging

  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY_STAGING" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    - ssh $DEPLOY_STAGING_SSH_HOST "docker login -u $DOCKER_REG_USER -p $DOCKER_REG_PASSWORD 10.0.0.130:1443"
    - ssh $DEPLOY_STAGING_SSH_HOST "docker pull $CONTAINER_IMAGE"



    # docker standalone
    #- ssh $DEPLOY_STAGING_SSH_HOST "docker stop $DOCKER_CONTAINER_NAME || true"
    #- ssh $DEPLOY_STAGING_SSH_HOST "docker rm $DOCKER_CONTAINER_NAME || true"
    #- ssh $DEPLOY_STAGING_SSH_HOST "docker run --detach -P -e VIRTUAL_HOST=$VHOST --name $DOCKER_CONTAINER_NAME $CONTAINER_IMAGE"

    # cleanup old docker images - https://blog.cynexia.com/varlibdockeraufsdiff-is-consuming-entire-drive/
    #- ssh $DEPLOY_STAGING_SSH_HOST 'docker rmi $(docker images -aq --filter=dangling=true) || true'



    # docker compose
    - ssh $DEPLOY_STAGING_SSH_HOST "mkdir -p ~/browsergame/$CI_COMMIT_REF_SLUG"
    - scp -r ./Docker/docker-compose.yml $DEPLOY_STAGING_SSH_HOST:~/browsergame/docker-compose.yml
    - ssh $DEPLOY_STAGING_SSH_HOST "cd ~/browsergame/$CI_COMMIT_REF_SLUG && export CI_COMMIT_SHA=$CI_COMMIT_SHA && export BRANCH=$CI_COMMIT_REF_SLUG && export CONTAINER_IMAGE=$CONTAINER_IMAGE && docker-compose -p $CI_COMMIT_REF_SLUG up -d"
    

    


# https://blog.kontena.io/continuous-delivery-with-gitlabci/
job_stop_deploy_staging:
  stage: stop_deploy
  image: kroniak/ssh-client

  dependencies:
    - job_deploy_staging

  variables:
  #  GIT_STRATEGY: none # we need git for docker-compose

    CONTAINER_IMAGE: 10.0.0.130:1443/browsergame/browsergame:$CI_COMMIT_REF_SLUG
    DOCKER_CONTAINER_NAME: browsergame_$CI_COMMIT_REF_SLUG
    VHOST: $CI_COMMIT_REF_SLUG.gamez.mynode.space

  when: manual
  environment:
    name: staging/$CI_COMMIT_REF_SLUG
    action: stop
  
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY_STAGING" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # docker standalone
    #- ssh $DEPLOY_STAGING_SSH_HOST "docker stop $DOCKER_CONTAINER_NAME || true"
    #- ssh $DEPLOY_STAGING_SSH_HOST "docker rm $DOCKER_CONTAINER_NAME"

    # docker compose
    - scp -r ./Docker/docker-compose.yml $DEPLOY_STAGING_SSH_HOST:~/browsergame/docker-compose.yml
    - ssh $DEPLOY_STAGING_SSH_HOST "cd ~/browsergame/$CI_COMMIT_REF_SLUG && export BRANCH=$CI_COMMIT_REF_SLUG && export CONTAINER_IMAGE=$CONTAINER_IMAGE && docker-compose -p $CI_COMMIT_REF_SLUG down"
    - ssh $DEPLOY_STAGING_SSH_HOST "cd ~/browsergame && rm -f ./$CI_COMMIT_REF_SLUG"

    # cleanup old docker images - https://blog.cynexia.com/varlibdockeraufsdiff-is-consuming-entire-drive/
    - ssh $DEPLOY_STAGING_SSH_HOST 'docker rmi $(docker images -aq --filter=dangling=true) || true'



## check API with postman docs
job_test_postman_api:
  stage: stop_deploy
  image: 
    name: postman/newman
    # ATTENTION: this container hash no shell as entrypoint -> set it
    entrypoint: [""]

  dependencies:
    - job_deploy_staging

#  allow_failure: true

  # https://medium.com/@vdespa/how-to-run-postman-api-tests-with-newman-in-gitlab-ci-the-proper-way-b5a9f6076d79
  script:
    - ls -ahl && ls -ahl ./docs && ls -ahl ./docs/RestAPI
    - newman --version
    - newman --help
    - newman run --help
    # https://github.com/postmanlabs/newman/issues/1590
    - newman run ./docs/RestAPI/BrowsergameAPI.postman_collection.json --environment="./docs/RestAPI/BrowsergameAPI.postman_environment.json" --reporter-junit-export="./newman-report.xml" -r junit --reporters="junit,cli" --global-var "url=http://$CI_COMMIT_REF_SLUG.gamez.mynode.space"
    - ls -ahl
    - find . -name "*.xml"
    - find / -name "*.xml"

  artifacts:
      expire_in: 15 minutes
      paths:
        - ./*.xml
      reports:
        junit: ./*.xml