<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="SkiaSharp" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bjarnoy.Domain\Bjarnoy.Domain.csproj" />
    <ProjectReference Include="..\..\src\Bjarnoy.Infrastructure\Bjarnoy.Infrastructure.csproj" />
  </ItemGroup>

</Project>
