// <auto-generated />
using System;
using Bjarnoy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bjarnoy.Migrations.PostgreSql.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260824173423_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.IslandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CentreQ")
                        .HasColumnType("integer");

                    b.Property<int>("CentreR")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StartPositions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TileCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Index")
                        .IsUnique();

                    b.ToTable("islands", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BeachThreshold")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ForestRockiness")
                        .HasColumnType("double precision");

                    b.Property<int>("IslandCellSize")
                        .HasColumnType("integer");

                    b.Property<double>("IslandChance")
                        .HasColumnType("double precision");

                    b.Property<double>("IslandMaxRadius")
                        .HasColumnType("double precision");

                    b.Property<double>("IslandMinRadius")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumIslandTiles")
                        .HasColumnType("integer");

                    b.Property<double>("MountainRockiness")
                        .HasColumnType("double precision");

                    b.Property<double>("MountainThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Radius")
                        .HasColumnType("integer");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.IslandEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Islands")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Navigation("Islands");
                });
#pragma warning restore 612, 618
        }
    }
}
