// <auto-generated />
using System;
using Bjarnoy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bjarnoy.Migrations.PostgreSql.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.BuildOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Q")
                        .HasColumnType("integer");

                    b.Property<int>("R")
                        .HasColumnType("integer");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "Q", "R")
                        .IsUnique();

                    b.ToTable("build_orders", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.IslandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CentreQ")
                        .HasColumnType("integer");

                    b.Property<int>("CentreR")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StartPositions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TileCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Index")
                        .IsUnique();

                    b.ToTable("islands", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.PlacedBuildingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Q")
                        .HasColumnType("integer");

                    b.Property<int>("R")
                        .HasColumnType("integer");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "Q", "R")
                        .IsUnique();

                    b.ToTable("placed_buildings", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.SettlementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("CapacityFood")
                        .HasColumnType("double precision");

                    b.Property<double>("CapacityIron")
                        .HasColumnType("double precision");

                    b.Property<double>("CapacityStone")
                        .HasColumnType("double precision");

                    b.Property<double>("CapacityWood")
                        .HasColumnType("double precision");

                    b.Property<int>("CentreQ")
                        .HasColumnType("integer");

                    b.Property<int>("CentreR")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FoundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IslandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("RateFood")
                        .HasColumnType("double precision");

                    b.Property<double>("RateIron")
                        .HasColumnType("double precision");

                    b.Property<double>("RateStone")
                        .HasColumnType("double precision");

                    b.Property<double>("RateWood")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("StockFood")
                        .HasColumnType("double precision");

                    b.Property<double>("StockIron")
                        .HasColumnType("double precision");

                    b.Property<double>("StockStone")
                        .HasColumnType("double precision");

                    b.Property<double>("StockWood")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IslandId");

                    b.HasIndex("WorldId", "OwnerId")
                        .IsUnique();

                    b.HasIndex("WorldId", "CentreQ", "CentreR")
                        .IsUnique();

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegacyPlayerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("BeachThreshold")
                        .HasColumnType("double precision");

                    b.Property<long>("ClockOffsetTicks")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ForestRockiness")
                        .HasColumnType("double precision");

                    b.Property<int>("IslandCellSize")
                        .HasColumnType("integer");

                    b.Property<double>("IslandChance")
                        .HasColumnType("double precision");

                    b.Property<double>("IslandMaxRadius")
                        .HasColumnType("double precision");

                    b.Property<double>("IslandMinRadius")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumIslandTiles")
                        .HasColumnType("integer");

                    b.Property<double>("MountainRockiness")
                        .HasColumnType("double precision");

                    b.Property<double>("MountainThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Radius")
                        .HasColumnType("integer");

                    b.Property<int>("RunState")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RunStateSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.BuildOrderEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.SettlementEntity", "Settlement")
                        .WithMany("Queue")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.IslandEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Islands")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.PlacedBuildingEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.SettlementEntity", "Settlement")
                        .WithMany("Buildings")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.SettlementEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.IslandEntity", "Island")
                        .WithMany()
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bjarnoy.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Settlements")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Island");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.SettlementEntity", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Navigation("Islands");

                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
