// Regenerates src/shared/confluence-representability.json from the frontend predicate.
//   cd src/frontend && npx tsx ../../scripts/regen-goldens/confluence-representability-golden.ts
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { confluenceKind, confluenceKindWithWidths } from '../../src/frontend/src/lib/map/types';

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../../src/shared/confluence-representability.json');
const rows: { out: number; inA: number; inB: number; kind: string | null }[] = [];
for (let o = 0; o < 6; o++) {
  for (let a = 0; a < 6; a++) {
    for (let b = a + 1; b < 6; b++) rows.push({ out: o, inA: a, inB: b, kind: confluenceKind(a, b, o) });
  }
}
// A river inflow and a stream inflow (ordered: which is which matters to the width, not the geometry).
const riverStreamRows: { out: number; riverIn: number; streamIn: number; kind: string | null }[] = [];
for (let o = 0; o < 6; o++) {
  for (let r = 0; r < 6; r++) {
    for (let st = 0; st < 6; st++) {
      if (r !== st) riverStreamRows.push({ out: o, riverIn: r, streamIn: st, kind: confluenceKindWithWidths(r, true, st, false, o) });
    }
  }
}
const doc = {
  _comment:
    'Which (inflow, inflow, outflow) direction triples the art can draw as a confluence: "narrow" (rivertile_y_narrow / smallwide_y_narrow: inflows at out+2 and out+3), "wide" (ywide: out+2 and out+4) or null; `riverStreamRows` (one river inflow, one stream inflow, every out and every ordered pair) is \"riverstreamwide\" (rivertile_riverstream_ywide: the wide-Y edge set) or null. Directions are TileOrientation indices (E=0 NE=1 NW=2 W=3 SW=4 SE=5). Rows are every out and every unordered inflow pair (riverStreamRows: every ordered pair). Generated by scripts/regen-goldens/confluence-representability-golden.ts from the frontend predicate (confluenceKind, types.ts); RiverConfluenceParityTests (backend RiverConfluence.Classify) and confluenceRepresentability.golden.test.ts assert it.',
  rows,
  riverStreamRows,
};
writeFileSync(out, JSON.stringify(doc, null, 1) + '\n');
console.log(`wrote ${out} (${rows.filter((r) => r.kind).length} representable of ${rows.length})`);
