// Regenerates src/shared/terrain-checksum-golden.json from the frontend generator.
//   cd src/frontend && npx tsx ../../scripts/regen-goldens/terrain-checksum-golden.ts
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CHECKSUM_SCAN, terrainChecksums } from '../../src/frontend/src/lib/map/testing/terrainChecksums';

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../../src/shared/terrain-checksum-golden.json');
const seeds = [1, 7, 42, 1337, -5, 2147483, 0];
async function main() {
  const entries = [];
  for (const seed of seeds) entries.push({ seed, ...(await terrainChecksums(seed)) });
  const doc = {
    _comment:
      'Cross-language parity fixture for terrain, orientation and variant over the whole default world. For each seed, SHA-256 of (a) the first letter of every hex\'s terrain wire name, (b) its orientation index (TileOrientation numeric value) and (c) its variant digit (sea pinned to 0: the backend has no coastal-water variant weighting), all in q-major order over hexes with |q|,|r| <= scan.extent stepping by scan.stride and inside the default world radius. Generated by scripts/regen-goldens/terrain-checksum-golden.ts from the frontend generator (worldGenerator.ts); TerrainSamplerParityTests and TileFeatureTests (backend) and terrainChecksum.golden.test.ts (frontend) recompute the digests with their own implementation.',
    scan: CHECKSUM_SCAN,
    seeds: entries,
  };
  writeFileSync(out, JSON.stringify(doc, null, 2) + '\n');
  console.log(`wrote ${out}`);
}

void main();
