// Regenerates src/shared/wasted-terrain-golden.json from the frontend generator: for a few
// seeds, every hex of a window around the smallest wasted island whose wastedTerrainAt is land.
//   cd src/frontend && npx tsx ../../scripts/regen-goldens/wasted-terrain-golden.ts
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { oddQToAxial } from '../../src/frontend/src/lib/hex/coords';
import {
  DEFAULT_GENERATION,
  enumerateIslandShapes,
  wastedTerrainAt,
} from '../../src/frontend/src/lib/map/worldGenerator';

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../../src/shared/wasted-terrain-golden.json');
const seeds = [40, 16, 6];

const scenarios = seeds.map((seed) => {
  const world = { seed, generation: { ...DEFAULT_GENERATION, worldRadius: 1000 } };
  const wasted = enumerateIslandShapes(world, true);
  if (wasted.length === 0) throw new Error(`seed ${seed} has no wasted islands`);
  const island = wasted.reduce((a, b) => (b.reach < a.reach ? b : a));
  const centre = oddQToAxial({ col: Math.floor(island.cx + 0.5), row: Math.floor(island.cy + 0.5) });
  const radius = Math.ceil(island.reach) + 6;
  const hexes: [number, number, string][] = [];
  for (let dq = -radius; dq <= radius; dq++) {
    const rMin = Math.max(-radius, -dq - radius);
    const rMax = Math.min(radius, -dq + radius);
    for (let dr = rMin; dr <= rMax; dr++) {
      const q = centre.q + dq;
      const r = centre.r + dr;
      const terrain = wastedTerrainAt(q, r, world);
      if (terrain !== 'sea') hexes.push([q, r, terrain]);
    }
  }
  hexes.sort((a, b) => (a[0] !== b[0] ? a[0] - b[0] : a[1] - b[1]));
  return { seed, centreQ: centre.q, centreR: centre.r, radius, hexes };
});

const comment =
  'Cross-language parity fixture for wasted-island terrain (TerrainSampler.WastedTerrainAt backend / wastedTerrainAt frontend): for each seed, every hex within `radius` of (centreQ, centreR) - a window around the smallest wasted island of the default-size world - whose wastedTerrainAt is land, sorted by (q, r). Generated by scripts/regen-goldens/wasted-terrain-golden.ts from the frontend generator; WastedTerrainGoldenTests.cs (backend) and wastedTerrain.golden.test.ts (frontend) each recompute against this fixture using their own production sampler and assert the frozen `hexes` list.';
const body = scenarios
  .map(
    (s) =>
      `    {\n      "seed": ${s.seed},\n      "centreQ": ${s.centreQ},\n      "centreR": ${s.centreR},\n      "radius": ${s.radius},\n      "hexes": [\n${s.hexes.map((h) => '        ' + JSON.stringify(h)).join(',\n')}\n      ]\n    }`,
  )
  .join(',\n');
writeFileSync(out, `{\n  "_comment": ${JSON.stringify(comment)},\n  "scenarios": [\n${body}\n  ]\n}\n`);
for (const s of scenarios) console.log('seed', s.seed, 'centre', s.centreQ, s.centreR, 'radius', s.radius, 'hexes', s.hexes.length);
