// <auto-generated />
using System;
using Bjarnoy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bjarnoy.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260829091700_AddGuilds")]
    partial class AddGuilds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.BuildOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletesAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "Q", "R")
                        .IsUnique();

                    b.ToTable("build_orders", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildBoardPostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("guild_board_posts", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildBoardTopicEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("guild_board_topics", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DisbandedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique();

                    b.HasIndex("WorldId", "Tag")
                        .IsUnique();

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildMembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FeePaidThroughAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("guild_memberships", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildPeaceTreatyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProposerGuildId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RespondedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetGuildId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProposerGuildId", "TargetGuildId");

                    b.HasIndex("TargetGuildId");

                    b.ToTable("guild_peace_treaties", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.IslandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CentreQ")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentreR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiverTiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPositions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TileCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Index")
                        .IsUnique();

                    b.ToTable("islands", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.PlacedBuildingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "Q", "R")
                        .IsUnique();

                    b.ToTable("placed_buildings", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.SettlementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("CapacityFood")
                        .HasColumnType("REAL");

                    b.Property<double>("CapacityIron")
                        .HasColumnType("REAL");

                    b.Property<double>("CapacityStone")
                        .HasColumnType("REAL");

                    b.Property<double>("CapacityWood")
                        .HasColumnType("REAL");

                    b.Property<int>("CentreQ")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentreR")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FoundedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IslandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("RateFood")
                        .HasColumnType("REAL");

                    b.Property<double>("RateIron")
                        .HasColumnType("REAL");

                    b.Property<double>("RateStone")
                        .HasColumnType("REAL");

                    b.Property<double>("RateWood")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("SettledAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("StockFood")
                        .HasColumnType("REAL");

                    b.Property<double>("StockIron")
                        .HasColumnType("REAL");

                    b.Property<double>("StockStone")
                        .HasColumnType("REAL");

                    b.Property<double>("StockWood")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IslandId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldId", "OwnerId")
                        .IsUnique();

                    b.HasIndex("WorldId", "CentreQ", "CentreR")
                        .IsUnique();

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            NormalizedUserName = "abandoned",
                            PasswordHash = "SYSTEM-ACCOUNT-NO-LOGIN",
                            Role = 0,
                            Status = 0,
                            UserName = "Abandoned"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            NormalizedUserName = "barbarians",
                            PasswordHash = "SYSTEM-ACCOUNT-NO-LOGIN",
                            Role = 0,
                            Status = 0,
                            UserName = "Barbarians"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            NormalizedUserName = "endboss",
                            PasswordHash = "SYSTEM-ACCOUNT-NO-LOGIN",
                            Role = 0,
                            Status = 0,
                            UserName = "Endboss"
                        });
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("BeachThreshold")
                        .HasColumnType("REAL");

                    b.Property<long>("ClockOffsetTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndbossAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndbossTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ForestRockiness")
                        .HasColumnType("REAL");

                    b.Property<int>("IslandCellSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("IslandChance")
                        .HasColumnType("REAL");

                    b.Property<double>("IslandMaxRadius")
                        .HasColumnType("REAL");

                    b.Property<double>("IslandMinRadius")
                        .HasColumnType("REAL");

                    b.Property<bool>("JoinsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumIslandTiles")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MountainRockiness")
                        .HasColumnType("REAL");

                    b.Property<double>("MountainThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Radius")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RunStateSince")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpeedFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0);

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.BuildOrderEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.SettlementEntity", "Settlement")
                        .WithMany("Queue")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildBoardPostEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.GuildBoardTopicEntity", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildBoardTopicEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.GuildEntity", "Guild")
                        .WithMany("Topics")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildMembershipEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.GuildEntity", "Guild")
                        .WithMany("Memberships")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bjarnoy.Infrastructure.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildPeaceTreatyEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.GuildEntity", "ProposerGuild")
                        .WithMany()
                        .HasForeignKey("ProposerGuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bjarnoy.Infrastructure.Entities.GuildEntity", "TargetGuild")
                        .WithMany()
                        .HasForeignKey("TargetGuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProposerGuild");

                    b.Navigation("TargetGuild");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.IslandEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Islands")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.PlacedBuildingEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.SettlementEntity", "Settlement")
                        .WithMany("Buildings")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.SettlementEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.IslandEntity", "Island")
                        .WithMany()
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bjarnoy.Infrastructure.Entities.UserEntity", "Owner")
                        .WithMany("Settlements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bjarnoy.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Settlements")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Island");

                    b.Navigation("Owner");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildBoardTopicEntity", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.GuildEntity", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.SettlementEntity", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Navigation("Islands");

                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
