// <auto-generated />
using System;
using Bjarnoy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bjarnoy.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.BuildOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletesAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "Q", "R")
                        .IsUnique();

                    b.ToTable("build_orders", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.IslandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CentreQ")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentreR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPositions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TileCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Index")
                        .IsUnique();

                    b.ToTable("islands", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.PlacedBuildingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "Q", "R")
                        .IsUnique();

                    b.ToTable("placed_buildings", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.SettlementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CapacityFood")
                        .HasColumnType("REAL");

                    b.Property<double>("CapacityIron")
                        .HasColumnType("REAL");

                    b.Property<double>("CapacityStone")
                        .HasColumnType("REAL");

                    b.Property<double>("CapacityWood")
                        .HasColumnType("REAL");

                    b.Property<int>("CentreQ")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentreR")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FoundedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IslandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("RateFood")
                        .HasColumnType("REAL");

                    b.Property<double>("RateIron")
                        .HasColumnType("REAL");

                    b.Property<double>("RateStone")
                        .HasColumnType("REAL");

                    b.Property<double>("RateWood")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("SettledAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("StockFood")
                        .HasColumnType("REAL");

                    b.Property<double>("StockIron")
                        .HasColumnType("REAL");

                    b.Property<double>("StockStone")
                        .HasColumnType("REAL");

                    b.Property<double>("StockWood")
                        .HasColumnType("REAL");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IslandId");

                    b.HasIndex("WorldId", "CentreQ", "CentreR")
                        .IsUnique();

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("BeachThreshold")
                        .HasColumnType("REAL");

                    b.Property<long>("ClockOffsetTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ForestRockiness")
                        .HasColumnType("REAL");

                    b.Property<int>("IslandCellSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("IslandChance")
                        .HasColumnType("REAL");

                    b.Property<double>("IslandMaxRadius")
                        .HasColumnType("REAL");

                    b.Property<double>("IslandMinRadius")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumIslandTiles")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MountainRockiness")
                        .HasColumnType("REAL");

                    b.Property<double>("MountainThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Radius")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RunStateSince")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.BuildOrderEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.SettlementEntity", "Settlement")
                        .WithMany("Queue")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.IslandEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Islands")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.PlacedBuildingEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.SettlementEntity", "Settlement")
                        .WithMany("Buildings")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.SettlementEntity", b =>
                {
                    b.HasOne("Bjarnoy.Infrastructure.Entities.IslandEntity", "Island")
                        .WithMany()
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bjarnoy.Infrastructure.Entities.WorldEntity", "World")
                        .WithMany("Settlements")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Island");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.SettlementEntity", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("Bjarnoy.Infrastructure.Entities.WorldEntity", b =>
                {
                    b.Navigation("Islands");

                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
