using System.Text.Json;
using Bjarnoy.Domain.World;

namespace Bjarnoy.Domain.Tests;

/// <summary>
/// The island shape's cross-language anti-drift guard.
/// <c>src/shared/island-shape-golden.json</c> was generated by
/// <c>scripts/regen-goldens/island-shape-golden.ts</c> from the frontend's own
/// <c>worldGenerator.ts</c>; this suite recomputes every island cell shape and a few
/// hundred depth/terrain samples per scenario with <see cref="TerrainSampler"/> and
/// asserts them <em>exactly</em> (doubles bit for bit). The frontend's
/// <c>islandShape.golden.test.ts</c> asserts the same file against the TypeScript.
/// </summary>
public class IslandShapeGoldenTests
{
    private static readonly IReadOnlyList<JsonElement> Scenarios = Load();

    public static TheoryData<string> Names()
    {
        var data = new TheoryData<string>();
        foreach (var s in Scenarios)
        {
            data.Add(s.GetProperty("name").GetString()!);
        }

        return data;
    }

    private static JsonElement Scenario(string name) =>
        Scenarios.Single(s => s.GetProperty("name").GetString() == name);

    private static WorldGenerationOptions OptionsOf(JsonElement scenario)
    {
        var g = scenario.GetProperty("generation");
        double D(string key) => g.GetProperty(key).GetDouble();
        int I(string key) => g.GetProperty(key).GetInt32();

        return new WorldGenerationOptions
        {
            Seed = scenario.GetProperty("seed").GetInt32(),
            Radius = I("worldRadius"),
            IslandCellSize = I("islandCellSize"),
            IslandChance = D("islandChance"),
            IslandMinWidth = D("islandMinWidth"),
            IslandMaxWidth = D("islandMaxWidth"),
            IslandMinSegments = I("islandMinSegments"),
            IslandMaxSegments = I("islandMaxSegments"),
            IslandMinElongation = D("islandMinElongation"),
            IslandMaxElongation = D("islandMaxElongation"),
            IslandMinBend = D("islandMinBend"),
            IslandMaxBend = D("islandMaxBend"),
            IslandCoastWarp = D("islandCoastWarp"),
            IslandCoastWarpScale = D("islandCoastWarpScale"),
            IslandCoastNoise = D("islandCoastNoise"),
            IslandCoastNoiseScale = D("islandCoastNoiseScale"),
            IslandSmallShare = D("islandSmallShare"),
            IslandLargeShare = D("islandLargeShare"),
            BeachThreshold = D("beachThreshold"),
            MountainThreshold = D("mountainThreshold"),
            MountainRockiness = D("mountainRockiness"),
            ForestRockiness = D("forestRockiness"),
        };
    }

    private static double[] Doubles(JsonElement array) => [.. array.EnumerateArray().Select(e => e.GetDouble())];

    [Theory]
    [MemberData(nameof(Names))]
    public void Island_cell_shapes_match_the_frontend_bit_for_bit(string name)
    {
        var scenario = Scenario(name);
        var sampler = new TerrainSampler(OptionsOf(scenario));

        var expected = scenario.GetProperty("shapes").EnumerateArray().ToList();
        var actual = sampler.EnumerateIslandShapes().ToList();

        Assert.Equal(expected.Count, actual.Count);
        for (var i = 0; i < expected.Count; i++)
        {
            var e = expected[i];
            var a = actual[i];
            var label = $"{name} island #{i} (cell {a.CellCol},{a.CellRow})";
            Assert.True(e.GetProperty("cellCol").GetInt32() == a.CellCol && e.GetProperty("cellRow").GetInt32() == a.CellRow, label + ": cell");
            Assert.True(e.GetProperty("cx").GetDouble() == a.CentreX, label + ": cx");
            Assert.True(e.GetProperty("cy").GetDouble() == a.CentreY, label + ": cy");
            Assert.True(e.GetProperty("reach").GetDouble() == a.Reach, label + ": reach");
            Assert.True(e.GetProperty("clamp").GetDouble() == a.ClampFactor, label + ": clamp");
            Assert.Equal(e.GetProperty("sizeClass").GetString(), a.SizeClass.ToString().ToLowerInvariant());
            Assert.Equal(Doubles(e.GetProperty("spineX")), a.SpineX);
            Assert.Equal(Doubles(e.GetProperty("spineY")), a.SpineY);
            Assert.Equal(Doubles(e.GetProperty("width")), a.Width);
            Assert.Equal(Doubles(e.GetProperty("isletX")), a.IsletX);
            Assert.Equal(Doubles(e.GetProperty("isletY")), a.IsletY);
            Assert.Equal(Doubles(e.GetProperty("isletRadius")), a.IsletRadius);
            Assert.True(
                e.GetProperty("minCol").GetInt32() == a.MinCol && e.GetProperty("maxCol").GetInt32() == a.MaxCol
                && e.GetProperty("minRow").GetInt32() == a.MinRow && e.GetProperty("maxRow").GetInt32() == a.MaxRow,
                label + ": scan box");
        }
    }

    [Theory]
    [MemberData(nameof(Names))]
    public void Wasted_island_cells_match_the_frontend(string name)
    {
        var scenario = Scenario(name);
        var sampler = new TerrainSampler(OptionsOf(scenario));

        var expected = scenario.GetProperty("wastedShapes").EnumerateArray().ToList();
        var actual = sampler.EnumerateIslandShapes(wasted: true).ToList();

        Assert.Equal(expected.Count, actual.Count);
        for (var i = 0; i < expected.Count; i++)
        {
            Assert.True(expected[i].GetProperty("cellCol").GetInt32() == actual[i].CellCol, $"{name} wasted #{i}: cellCol");
            Assert.True(expected[i].GetProperty("cellRow").GetInt32() == actual[i].CellRow, $"{name} wasted #{i}: cellRow");
            Assert.True(expected[i].GetProperty("cx").GetDouble() == actual[i].CentreX, $"{name} wasted #{i}: cx");
            Assert.True(expected[i].GetProperty("cy").GetDouble() == actual[i].CentreY, $"{name} wasted #{i}: cy");
            Assert.True(expected[i].GetProperty("reach").GetDouble() == actual[i].Reach, $"{name} wasted #{i}: reach");
        }
    }

    [Theory]
    [MemberData(nameof(Names))]
    public void Depth_and_terrain_match_the_frontend_at_every_sampled_hex(string name)
    {
        var scenario = Scenario(name);
        var sampler = new TerrainSampler(OptionsOf(scenario));
        var checkedLand = 0;
        var checkedWasted = 0;

        foreach (var row in scenario.GetProperty("samples").EnumerateArray())
        {
            var coord = new HexCoord(row[0].GetInt32(), row[1].GetInt32());

            AssertDepth(name, coord, "green depth", row[2], sampler.IslandDepthAt(coord));
            AssertDepth(name, coord, "wasted depth", row[3], sampler.WastedDepthAt(coord));
            Assert.True(
                row[4].GetString() == sampler.TerrainAt(coord).ToWireName(),
                $"{name} {coord}: terrain expected {row[4].GetString()}, got {sampler.TerrainAt(coord).ToWireName()}");
            Assert.True(
                row[5].GetString() == sampler.WastedTerrainAt(coord).ToWireName(),
                $"{name} {coord}: wasted terrain expected {row[5].GetString()}, got {sampler.WastedTerrainAt(coord).ToWireName()}");

            if (row[2].ValueKind != JsonValueKind.Null)
            {
                checkedLand++;
            }

            if (row[3].ValueKind != JsonValueKind.Null)
            {
                checkedWasted++;
            }
        }

        // The fixture must actually exercise islands, not just sea.
        Assert.True(checkedLand > 20, $"{name}: only {checkedLand} sampled hexes were on a green island");
        if (scenario.GetProperty("wastedShapes").GetArrayLength() > 0)
        {
            Assert.True(checkedWasted > 0, $"{name}: wasted islands exist but no sample hit one");
        }
    }

    private static void AssertDepth(string name, HexCoord coord, string what, JsonElement expected, double? actual)
    {
        if (expected.ValueKind == JsonValueKind.Null)
        {
            Assert.True(actual is null, $"{name} {coord}: {what} expected sea, got {actual:R}");
            return;
        }

        Assert.True(
            actual is not null && expected.GetDouble() == actual.Value,
            $"{name} {coord}: {what} expected {expected.GetDouble():R}, got {actual:R}");
    }

    private static List<JsonElement> Load()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Bjarnoy.slnx")))
        {
            dir = dir.Parent;
        }

        if (dir?.Parent is null)
        {
            throw new InvalidOperationException("Could not locate Bjarnoy.slnx while searching for the repo root.");
        }

        var json = File.ReadAllText(Path.Combine(dir.Parent.FullName, "shared", "island-shape-golden.json"));
        using var doc = JsonDocument.Parse(json);
        return [.. doc.RootElement.GetProperty("scenarios").EnumerateArray().Select(e => e.Clone())];
    }
}
