# Database migration configuration

.migration-template:
  stage: build
  image: golang:1.21
  services:
    - postgres:14.3-alpine
  variables:
    POSTGRES_HOST: "postgres" # should match the name of the service
    SERVICE_DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}?sslmode=disable

atlas-migration:
  extends: .migration-template
  script:
    - which atlas || (curl -sSf https://atlasgo.sh | sh -s -- --community)
    - cd sql
    - atlas migrate hash
    - atlas migrate validate --env ci
    - atlas migrate apply --env ci --dry-run
    - atlas migrate apply --env ci
    - atlas migrate status --env ci
  artifacts:
    reports:
      # Archive migration status for reference
      junit: "**/migration-status.xml"
    when: always
