.schema-gen-template:
  stage: schema-gen
  image: node:22-alpine
  services:
    #- name: $CI_REGISTRY_IMAGE/api:$CI_COMMIT_SHA # this uses the auto env from gitlab
    - name: $CONTAINER_IMAGE:$CI_COMMIT_SHA
      alias: api
      variables:
        ASPNETCORE_ENVIRONMENT: "gitlab"
  variables:
    NODE_TLS_REJECT_UNAUTHORIZED: "0"

generate-schema:
  extends: .schema-gen-template
  needs:
    - package
  before_script:
    - apk add --no-cache git curl
    - npm install -g openapi-typescript
    - chmod +x ./scripts/wait-for-api.sh
  script:
    - ./scripts/wait-for-api.sh
    # TODO clone frontend repo (its the same group in gitlab but named bg-frontend)
    - echo "$CI_SERVER_URL/$CI_PROJECT_NAMEPSACE/bg-frontend.git"
    - echo "$CI_PROJECT_URL/../bg-frontend.git"
    - echo "https://gitlab-ci-token:token@$CI_SERVER_URL/$CI_PROJECT_NAMESPACE/bg-frontend.git"
    - echo "https://gitlab-ci-token:token@$CI_SERVER_HOST/$CI_PROJECT_NAMESPACE/bg-frontend.git"
    #- git clone $CI_PROJECT_URL/../bg-frontend.git ./frontend
    # get permissions via gitlab-ci-token:${CI_JOB_TOKEN}@
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@$CI_SERVER_HOST/$CI_PROJECT_NAMESPACE/bg-frontend.git ./frontend
    #- openapi-typescript https://api:21047/swagger/v1/swagger.json -o ./map/src/api/types/apiSchema.ts --enum
    - openapi-typescript http://api:8080/openapi/v1.json -o ./frontend/map/src/api/types/apiSchema.ts --enum
    - git config user.email "ci@gitlab.com"
    - git config user.name "GitLab CI"
    - git add ./frontend/map/src/api/types/apiSchema.ts
    - 'git commit -m "+chore: auto update API schema" || echo "No changes to commit"'
    # create a new branch for the frontend repo
    - git checkout -b "feature/update-api-schema"
    #- git push origin HEAD:$CI_COMMIT_REF_NAME || echo "Nothing to push"
    - git push origin HEAD:feature/update-api-schema || echo "Nothing to push"

# generate schema via artifact from build and `src/BG.API/BG.API.json`
generate-schema-from-artifact:
  stage: schema-gen
  image: node:22-alpine
  needs:
    - build
  before_script:
    - apk add --no-cache git
    - npm install -g openapi-typescript
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@$CI_SERVER_HOST/$CI_PROJECT_NAMESPACE/bg-frontend.git ./frontend
    - openapi-typescript ./src/BG.API/BG.API.json -o ./frontend/map/src/api/types/apiSchema.ts --enum
    - cd ./frontend

    # show git changes
    - git status
    - git diff

    # add file
    - git config user.email "ci@andesia.org"
    - git config user.name "GitLab CI"
    - git add ./map/src/api/types/apiSchema.ts
    - git status
    - git diff

    # commit changes and push
    - 'git commit -m "+chore: auto update API schema" || echo "No changes to commit"'
    - git checkout -b "feature/update-api-schema"
    #- git push origin HEAD:feature/update-api-schema || echo "Nothing to push"

  artifacts:
    paths:
      - ./frontend/map/src/api/types/apiSchema.ts
