# Common test configuration and templates

.test-template:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  before_script:
    #  - dotnet tool install JunitXml.TestLogger --tool-path $CI_PROJECT_DIR/.dotnet/tools
    - dotnet restore

  cache:
    key: ${CI_COMMIT_REF_SLUG}-nuget
    paths:
      - .nuget/packages

  artifacts:
    reports:
      #coverage_report:
      #  coverage_format: cobertura
      #  path: "**/coverage.cobertura.xml"
      junit: "**/TestResults/results.xml"
    when: always

integration-test:
  extends: .test-template
  needs:
    - build
    - atlas-migration
  services:
    - name: postgres:16-alpine
      alias: postgres
      variables:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  variables:
    ConnectionStrings__DefaultConnection: "Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
  script:
    - dotnet test --filter "Category=Integration" --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "junit;LogFilePath=./TestResults/integration-tests.xml;MethodFormat=Class;FailureBodyFormat=Verbose"

unit-test:
  extends: .test-template
  needs:
    - build
    - atlas-migration
  script:
    - dotnet test --filter "Category!=Integration" --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "junit;LogFilePath=./TestResults/results.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
